### ISSUE TITLE
Habilitar download da foto do contato

### ISSUE THREAD

**Issue by ssteeltm** [sufficit/sufficit-quepasa#5]
Habilitar download da foto do contato.

Consultando o whatsmeow:

`[GetProfilePictureInfo](https://github.com/tulir/whatsmeow/blob/f650c10b0068/user.go#L209)
GetProfilePictureInfo gets the URL where you can download a WhatsApp user's profile picture or group's photo.

Optionally, you can pass the last known profile picture ID. If the profile picture hasn't changed, this will return nil with no error.
`

**Comment by hugodeco** [comment]
Implementado
https://github.com/sufficit/sufficit-quepasa/commit/b818c955f59324d52d43291cabeb9834c7dfb360
