### ISSUE TITLE
API: Habilitar Envio de Botoes ( simples, listas, links)

### ISSUE THREAD

**Issue by ssteeltm** [sufficit/sufficit-quepasa#6]
Habilitar Envio de Botoes ( simples, listas, links) na api do quepasa.
![image](https://user-images.githubusercontent.com/17302120/191274472-2252174b-5ec0-464f-99cf-4599c77ff519.png)
![image](https://user-images.githubusercontent.com/17302120/191274622-4e5eabbc-949d-4f83-9a99-caa35c55aaae.png)
![image](https://user-images.githubusercontent.com/17302120/191275055-715e103e-0408-4d96-bd86-23b80eb71973.png)

**Comment by hugodeco** [comment]
It should be great, but its not my day use, so help wanted.

**Comment by hugodeco** [comment]
Implementado, segue exemplo de mensagem.

*Bom dia !* Como podemos lhe ajudar hoje ? $buttons:[ (1)Suporte, (2)Financeiro ] escolha uma das opções a seguir:
