### ISSUE TITLE
Webhook: Possibilitar cadastrarmos variaveis custom

### ISSUE THREAD

**Issue by ssteeltm** [sufficit/sufficit-quepasa#8]
Possibilitar cadastrar variaveis custom, isso resolve o problema de multiplos fluxos que ficou pendente pensarmos. 
Ao inves de cadastrar os dados do chatwoot em cada fluxo para cada número, a saida seria injetar estes dados direto na reaposta do webhook do numero.
Podemos comecar com um simples campo para por  um json contendo o objeto e atributos.

Com isso acredito que vamos conseguir ter apenas um fluxo do n8n - quepasa to chatwoot.

Lembrando que isso se estende tambem para caso seja alterado do chatwoot para outro programa, pois ai ja passa a depender do n8n realizar a adaptação.

**Comment by hugodeco** [comment]
Já pensei nisso mas seria abusar da insegurança.
Enviar o token de volta pelo webhook.

Tudo bem que não é problema nosso cuidar dessa segurança de dados, mas ai é forçadão.
Tem que haver outro jeito.

**Comment by hugodeco** [comment]
Feito !
